/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasA;

import conector.conector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alcic
 */
public class AgregarDentista extends javax.swing.JFrame {

    public AgregarDentista() {
        initComponents();
        TextPrompt hini=new TextPrompt("HH:MM:SS",jTextFieldHoraInicial);
        TextPrompt hfin=new TextPrompt("HH:MM:SSS",jTextFieldHoraFinal);
                     
        this.setLocationRelativeTo(null);
        mostrartabla("");
        limpiar();
        jTextFieldIdHorario.setEnabled(false);
        jTextFieldIdDentista.setEnabled(false);
    }
    void limpiar(){
        jTextFieldIdHorario.setText("");
        jTextFieldHoraInicial.setText("");
        jTextFieldHoraFinal.setText("");
        jTextFieldDias.setText("");
        jTextFieldIdDentista.setText("");
        jTextFieldNombre.setText("");
        jTextFieldAppPA.setText("");
        jTextFieldAppMa.setText("");
        jTextFieldIdhorarioDENTISTA.setText("");
    }
    void mostrartabla(String valor){
    DefaultTableModel modelo=new DefaultTableModel();
    
    modelo.addColumn("Id Dentista");
    modelo.addColumn("Nombre ");
    modelo.addColumn("Apellido Paterno");
    modelo.addColumn("Apellido Materno");
    modelo.addColumn("Hora Inicial");
    modelo.addColumn("Hora final");
    modelo.addColumn("Dias");
    modelo.addColumn("Id Horario");
    
    jTableAgregarDentista.setModel(modelo);
    
    String sql="select dentista.idDentista,dentista.Nombre_dentista,dentista.Apellido1_dentista,dentista.Apellido2_dentista,horarios.hora_inicio,horarios.hora_final, horarios.dias,horarios.idHorarios FROM dentista, horarios where dentista.Horarios_idHorarios = horarios.idHorarios";
    String datos[]=new String[8];
    Statement st;
    
    try{
        st=cn.createStatement();
        ResultSet rs=st.executeQuery(sql);
        
        while (rs.next()){
        datos[0]=rs.getString(1);
        datos[1]=rs.getString(2);
        datos[2]=rs.getString(3);
        datos[3]=rs.getString(4);
        datos[4]=rs.getString(5);
        datos[5]=rs.getString(6);
        datos[6]=rs.getString(7);
        datos[7]=rs.getString(8);
       
        modelo.addRow(datos);
        }
        jTableAgregarDentista.setModel(modelo);
    }catch (SQLException e){
        System.err.print(e);
        JOptionPane.showMessageDialog(null, "Error al cargar cursos... Conectate al adminitrador");
    }
    
    
    
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1ATRAS = new javax.swing.JButton();
        jButtonExitM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgregarDentista = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIdDentista = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldAppPA = new javax.swing.JTextField();
        jTextFieldIdhorarioDENTISTA = new javax.swing.JTextField();
        jTextFieldAppMa = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonGuardarDENTIS = new javax.swing.JButton();
        jLabel7IdHorario = new javax.swing.JLabel();
        jTextFieldIdHorario = new javax.swing.JTextField();
        jTextFieldHoraInicial = new javax.swing.JTextField();
        jTextFieldHoraFinal = new javax.swing.JTextField();
        jLabelHoraFinal = new javax.swing.JLabel();
        jLabelHoraInicial = new javax.swing.JLabel();
        jLabelDias = new javax.swing.JLabel();
        jTextFieldDias = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonGuardarH = new javax.swing.JButton();
        jLabelFondoAD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1ATRAS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1ATRAS.setForeground(new java.awt.Color(51, 51, 255));
        jButton1ATRAS.setText("ATRAS");
        jButton1ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ATRASActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1ATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 100, 40));

        jButtonExitM.setText("EXIT");
        jButtonExitM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExitM, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 100, 50));

        jTableAgregarDentista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido Materno", "Apellido Paterno", "Edad", "Telefono", "Tratamiento"
            }
        ));
        jScrollPane1.setViewportView(jTableAgregarDentista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 600, 150));

        jLabel1.setText("ID Dentista");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 70, 20));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 60, 20));

        jLabel4.setText("Apellido Materno");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 100, -1));

        jLabel5.setText("Id Horario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 70, -1));

        jLabel6.setText("Apellido Paterno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 100, -1));
        getContentPane().add(jTextFieldIdDentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 260, -1));
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 260, -1));
        getContentPane().add(jTextFieldAppPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 260, -1));

        jTextFieldIdhorarioDENTISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdhorarioDENTISTAActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdhorarioDENTISTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 260, -1));
        getContentPane().add(jTextFieldAppMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 260, -1));

        jLabel3.setText("Dentista ");
        jPanel1.add(jLabel3);

        jLabel8.setText("                                ");
        jPanel1.add(jLabel8);

        jButtonGuardarDENTIS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGuardarDENTIS.setForeground(new java.awt.Color(51, 51, 255));
        jButtonGuardarDENTIS.setText("Guardar");
        jButtonGuardarDENTIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarDENTISActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardarDENTIS);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 380, 240));

        jLabel7IdHorario.setText("Id Horario");
        getContentPane().add(jLabel7IdHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 90, 20));

        jTextFieldIdHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIdHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 280, -1));

        jTextFieldHoraInicial.setText("00:00:00");
        jTextFieldHoraInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraInicialActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldHoraInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 280, -1));

        jTextFieldHoraFinal.setText("00:00:00");
        jTextFieldHoraFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraFinalActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 280, -1));

        jLabelHoraFinal.setText("Hora Final");
        getContentPane().add(jLabelHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 90, -1));

        jLabelHoraInicial.setText("Hora inicial");
        getContentPane().add(jLabelHoraInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 90, 20));

        jLabelDias.setText("Dias");
        getContentPane().add(jLabelDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 60, -1));
        getContentPane().add(jTextFieldDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 280, -1));

        jLabel11.setText("Horarios");
        jPanel2.add(jLabel11);

        jLabel7.setText("                                ");
        jPanel2.add(jLabel7);

        jButtonGuardarH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGuardarH.setForeground(new java.awt.Color(51, 51, 255));
        jButtonGuardarH.setText("Guardar");
        jButtonGuardarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarHActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGuardarH);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 400, 240));

        jLabelFondoAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesA/Agregar_Dentista.PNG"))); // NOI18N
        getContentPane().add(jLabelFondoAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ATRASActionPerformed
        Agregar me= new Agregar();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ATRASActionPerformed

    private void jButtonExitMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitMActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMActionPerformed

    private void jTextFieldIdhorarioDENTISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdhorarioDENTISTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdhorarioDENTISTAActionPerformed

    private void jTextFieldHoraFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraFinalActionPerformed

    private void jButtonGuardarDENTISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarDENTISActionPerformed
 
 try{
 
     if (jTextFieldNombre.getText().isEmpty()) 
     {
     JOptionPane.showMessageDialog(null, "Campo Nombre vacio");
     }
     ///////////////////////
     else if (jTextFieldAppPA.getText().isEmpty()) 
     {
     JOptionPane.showMessageDialog(null, "Campo Apellido Paterno vacio");
     } 
     //////////////
     else if (jTextFieldAppMa.getText().isEmpty()) 
     {
     JOptionPane.showMessageDialog(null, "Campo Apellido Materno vacio");
     } 
     //////////////
     
     else if (jTextFieldIdhorarioDENTISTA.getText().isEmpty()) 
     {
     JOptionPane.showMessageDialog(null, "Campo Dentista vacio");
     } 
     ////////////////
     else{
      PreparedStatement ps=cn.prepareStatement("INSERT INTO mydb.dentista (Nombre_dentista, Apellido1_dentista, Apellido2_dentista, Horarios_idHorarios) VALUES (?,?,?,?)");
      ps.setString(1, jTextFieldNombre.getText());
      ps.setString(2, jTextFieldAppPA.getText());
      ps.setString(3, jTextFieldAppMa.getText());
      ps.setString(4, jTextFieldIdhorarioDENTISTA.getText());
      
      ps.executeUpdate();
      JOptionPane.showMessageDialog(null, "Dentista Guardado");
      mostrartabla("");
      limpiar();      
     }
     
     
 }catch (Exception e){
     System.err.print(e);
     JOptionPane.showMessageDialog(null, "Error al guardar Dentista");
     
 }

  
 
    }//GEN-LAST:event_jButtonGuardarDENTISActionPerformed

    private void jTextFieldHoraInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraInicialActionPerformed

    private void jButtonGuardarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarHActionPerformed
        
 try{
     if (jTextFieldHoraInicial.getText().isEmpty()) 
     {
     JOptionPane.showMessageDialog(null, "Campo hora inicial vacio");
     }
     ///////////////////////////
     else if (jTextFieldHoraFinal.getText().isEmpty()) 
     {
     JOptionPane.showMessageDialog(null, "Campo hora final vacio");
     }
     ///////////////////////////////
     else if (jTextFieldDias.getText().isEmpty()) 
     {
     JOptionPane.showMessageDialog(null, "Campo dias vacio");
     }
     /////////////////////////
     
     
     else{
      PreparedStatement ps=cn.prepareStatement("INSERT INTO mydb.horarios (hora_inicio, hora_final, dias) VALUES (?,?,?)");
      ps.setString(1, jTextFieldHoraInicial.getText());
      ps.setString(2, jTextFieldHoraFinal.getText());
      ps.setString(3, jTextFieldDias.getText());
      
      ps.executeUpdate();
      JOptionPane.showMessageDialog(null, "Horario Guardado");
      mostrartabla("");
      limpiar();
      
     }
   
         } catch (SQLException e){
             System.err.print(e);
            JOptionPane.showMessageDialog(null, "Error al guardar Horaio");
     
 }
     

  
               
        
    }//GEN-LAST:event_jButtonGuardarHActionPerformed

    private void jTextFieldIdHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdHorarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarDentista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarDentista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ATRAS;
    private javax.swing.JButton jButtonExitM;
    private javax.swing.JButton jButtonGuardarDENTIS;
    private javax.swing.JButton jButtonGuardarH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7IdHorario;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelFondoAD;
    private javax.swing.JLabel jLabelHoraFinal;
    private javax.swing.JLabel jLabelHoraInicial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAgregarDentista;
    private javax.swing.JTextField jTextFieldAppMa;
    private javax.swing.JTextField jTextFieldAppPA;
    private javax.swing.JTextField jTextFieldDias;
    private javax.swing.JTextField jTextFieldHoraFinal;
    private javax.swing.JTextField jTextFieldHoraInicial;
    private javax.swing.JTextField jTextFieldIdDentista;
    private javax.swing.JTextField jTextFieldIdHorario;
    private javax.swing.JTextField jTextFieldIdhorarioDENTISTA;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
conector con=new conector ();
Connection cn=con.conexion();
}
