/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasA;

/**
 *
 * @author alcic
 */
public class EliminarD extends javax.swing.JFrame {

    /**
     * Creates new form EliminarD
     */
    public EliminarD() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2Cita = new javax.swing.JButton();
        jButton3Paciente = new javax.swing.JButton();
        jButton1Dentista = new javax.swing.JButton();
        jButton1ATRAS = new javax.swing.JButton();
        jButtonExitM = new javax.swing.JButton();
        jLabel1Eliminar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2Cita.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2Cita.setForeground(new java.awt.Color(51, 51, 255));
        jButton2Cita.setText("CITA");
        jButton2Cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CitaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Cita, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 170, 40));

        jButton3Paciente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3Paciente.setForeground(new java.awt.Color(51, 51, 255));
        jButton3Paciente.setText("PACIENTE");
        jButton3Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3PacienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3Paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 170, 40));

        jButton1Dentista.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1Dentista.setForeground(new java.awt.Color(51, 51, 255));
        jButton1Dentista.setText("DENTISTA");
        jButton1Dentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1DentistaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Dentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 170, 40));

        jButton1ATRAS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1ATRAS.setForeground(new java.awt.Color(51, 51, 255));
        jButton1ATRAS.setText("ATRAS");
        jButton1ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ATRASActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1ATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 80, 40));

        jButtonExitM.setText("EXIT");
        jButtonExitM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExitM, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 100, 50));

        jLabel1Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesA/Eliminar.1.PNG"))); // NOI18N
        getContentPane().add(jLabel1Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2CitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CitaActionPerformed
        EliminarCita me= new EliminarCita();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2CitaActionPerformed

    private void jButton3PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3PacienteActionPerformed
        EliminarPaciente me= new EliminarPaciente();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3PacienteActionPerformed

    private void jButton1DentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1DentistaActionPerformed
            EliminarDentista me= new EliminarDentista();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1DentistaActionPerformed

    private void jButton1ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ATRASActionPerformed
     Menu me= new Menu();
                me.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton1ATRASActionPerformed

    private void jButtonExitMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitMActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ATRAS;
    private javax.swing.JButton jButton1Dentista;
    private javax.swing.JButton jButton2Cita;
    private javax.swing.JButton jButton3Paciente;
    private javax.swing.JButton jButtonExitM;
    private javax.swing.JLabel jLabel1Eliminar;
    // End of variables declaration//GEN-END:variables
}
