/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasA;

/**
 *
 * @author alcic
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExitM = new javax.swing.JButton();
        jButtonCalendario = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonCaja = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonPasswordChange = new javax.swing.JButton();
        FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(922, 527));
        setMinimumSize(new java.awt.Dimension(922, 527));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExitM.setText("EXIT");
        jButtonExitM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExitM, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 100, 50));

        jButtonCalendario.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCalendario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonCalendario.setForeground(new java.awt.Color(51, 51, 255));
        jButtonCalendario.setText("CALENDARIO");
        getContentPane().add(jButtonCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jButtonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 120, -1));

        jButtonAgregar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonAgregar.setText("AGREGAR");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, 40));

        jButtonCaja.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCaja.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonCaja.setForeground(new java.awt.Color(51, 51, 255));
        jButtonCaja.setText("CAJA");
        jButtonCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCajaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 120, 40));

        jButtonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonEliminar.setText("ELIMINAR DATOS");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 180, 40));

        jButtonPasswordChange.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonPasswordChange.setForeground(new java.awt.Color(51, 51, 255));
        jButtonPasswordChange.setText("CAMBIAR CONTRASEÑA");
        getContentPane().add(jButtonPasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        FondoMenu.setBackground(new java.awt.Color(153, 153, 255));
        FondoMenu.setForeground(new java.awt.Color(51, 51, 255));
        FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesA/Menu.1.PNG"))); // NOI18N
        FondoMenu.setMaximumSize(new java.awt.Dimension(788, 444));
        FondoMenu.setMinimumSize(new java.awt.Dimension(788, 444));
        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitMActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitMActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
      Agregar me= new Agregar();
                me.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       Buscar me= new Buscar();
                me.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCajaActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
      EliminarD me= new EliminarD();
                me.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoMenu;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCaja;
    private javax.swing.JButton jButtonCalendario;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonExitM;
    private javax.swing.JButton jButtonPasswordChange;
    // End of variables declaration//GEN-END:variables
}
